services:
  blossom-phpfpm:
    restart: always
    image: blossomkc/php:8.1.33-2
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/ixed.8.1.lin:/usr/local/etc/ixed.8.1.lin
      - /var/www:/var/www
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  blossom-apache:
    restart: always
    image: httpd:2.4.62-alpine3.20
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./http/vhost.conf:/usr/local/apache2/conf/site-available/vhost.conf
      - ./http/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./http/cert:/certs
      - /var/www:/var/www
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  blossom-cron:
    restart: always
    image: blossomkc/cron:8.1.33-2
    environment:
      - HOST_HOSTNAME=${HOSTNAME} #linux only (on windows use COMPUTERNAME)
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/ixed.8.1.lin:/usr/local/etc/ixed.8.1.lin
      - /var/www:/var/www
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
