services:
  blossom-phpfpm:
    restart: always
    image: blossomkc/php:8.3.28-multiarch
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/ixed.8.3.lin:/usr/local/lib/php/extensions/no-debug-non-zts-20230831/ixed.8.3.lin
      - /var/www:/var/www
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  blossom-apache:
    restart: always
    image: httpd:2.4.67-alpine3.23
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./http/vhost.conf:/usr/local/apache2/conf/site-available/vhost.conf
      - ./http/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./http/cert:/certs
      - /var/www:/var/www
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  blossom-cron:
    restart: always
    image: blossomkc/cron:8.3.28-multiarch
    environment:
      - HOST_HOSTNAME=${HOSTNAME} #linux only (on windows use COMPUTERNAME)
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/ixed.8.3.lin:/usr/local/lib/php/extensions/no-debug-non-zts-20230831/ixed.8.3.lin
      #- ./php/ixed.8.3.lin:/usr/local/lib/php/extensions/no-debug-non-zts-20230831/ixed.8.3-arm.lin
      - /var/www:/var/www
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
